# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:24-alpine

ARG AUBE_VERSION=2.5.0
RUN wget -qO /tmp/aube.tar.gz "https://github.com/aubepkg/aube/releases/download/v${AUBE_VERSION}/aube-v${AUBE_VERSION}-$(uname -m)-unknown-linux-musl.tar.gz" \
    && tar -xzf /tmp/aube.tar.gz -C /usr/local/bin aube \
    && rm /tmp/aube.tar.gz

# Create app directory
WORKDIR /usr/src/app

# Copy dependency manifests
COPY package.json aube-lock.yaml ./

# Install dependencies (ignore scripts to avoid unintended auth triggers)
RUN aube install --frozen-lockfile --ignore-scripts

# Copy the rest of the application
COPY . .

# Expose no port because server communicates over stdio

# Set entrypoint
ENTRYPOINT ["node", "index.ts"]
